# docker-compose.yml
version: "3.9"

services:
  api:
    build:
    context: .
    dockerfile: rag_app/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - ollama
    volumes:
      - ./docs:/docs
    environment:
      - OLLAMA_URL=http://ollama:11434

  ollama:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama-data: